<div class="samples-panel-group panel-group">
	<div class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('Get Monitor Event Information') // TRANSLATE ?></h2>
		<p><?php echo sprintf($this->translate('Zend Server is not only a Continuous Delivery platform, it is also a problem detection and research platform. The Monitor component detects and records errors, performance problems and keeps watch over other Zend components as well. Any such system event is recorded with all associated and environment information to give a developer all the information he needs to pinpoint and resolve the issue.')) // TRANSLATE ?></p>
		<p><?php echo $this->translate('An event\'s full details are available through the WebAPI and can be used to find out what exactly happened, retrieve more information using other WebAPI requests and retrieve associated codetracing packages.') // TRANSLATE ?></p>
	
		<h3><?php echo $this->translate('monitorGetIssueDetails: Input Parameters') // TRANSLATE ?></h3>
		<p><?php echo sprintf($this->translate('monitorGetIssueDetails accepts two parameters - the issueId to retrieve information for and a limit on the number of event groups (event instances) to be retrieved in this request.')) // TRANSLATE ?></p>
		<p><?php echo sprintf($this->translate('The issueId variable can be found in a listing WebAPI action such as %smonitorGetIssuesByPredefinedFilter%s.'), '<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#monitorgetissueslistbypredefinedfilter.htm" target="_blank">', '</a>') // TRANSLATE ?></p>
		<h3><?php echo $this->translate('monitorGetIssueDetails: Output Structure') // TRANSLATE ?></h3>
		<p><?php echo $this->translate('The WebAPI action monitorGetIssueDetails returns all available information about the event and about its aggregated event groups. Event groups are aggregates of identical instances of the same event, which are created in order to cut down on space requirements for storing information. The response is composed of a few strucutures:') // TRANSLATE ?></p>
		<ul>
			<li><?php echo $this->translate('The issue element contains most basic and meta information about the event and the php environment in which it happened. This information is common to all associated Event Groups. Such information includes the Monitor Rule that generated the event, its last occurence timestamp, the number of times the event happened and associated codetracing package information.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('The generalDetails element contains details about the exact location of the error within the application - filepath, line number, the php error code, etc.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('The eventsGroup elements listed as part of the issue provide occurence-specific information such as concrete execution time and timestamp.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('The whatHappenedDetails element contains the some of the information found in the first associated eventsGroup element.') // TRANSLATE ?></li>
		</ul>
		<h3><?php echo $this->translate('monitorGetIssueDetails Common uses') // TRANSLATE ?></h3>
		<ul>
			<li><?php echo $this->translate('This action combines elements from the more detailed Event Groups WebAPI actions with surface information available in issues listing WebAPI actions. It acts as a good middle ground to either retrieve more high resolution details or to collect more symptomatic details before digging in.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('IssueDetails also returns the number of event groups found - a simplistic indicator of the intensity of the issue, as a traffic heavy page may produce many of these events.') // TRANSLATE ?></li>
		</ul>
		<h3><?php echo $this->translate('Getting even more detailed information') // TRANSLATE ?></h3>
		<ul>
			<li><?php echo sprintf($this->translate('You can retrieve more event groups using the %smonitorGetIssueEventGroups WebAPI action%s which allows you to retrieve lists limited to a number of rows but also adds offset control for pagination.'),'<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#monitorgetissueeventgroups.htm" target="_blank">', '</a>' ) // TRANSLATE ?></li>
			<li><?php echo sprintf($this->translate('You can get more specific environment information using the %smonitorGetEventGroupDetails WebAPI action%s. This action provides a list of PHP Super Globals\' values and other useful information about the moment the event was recorded.'),'<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#monitorgeteventgroupdetails.htm" target="_blank">', '</a>' ) // TRANSLATE ?></li>
		</ul>
	</div></div>
	<div class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('WebAPI request example') // TRANSLATE ?></h2>
		<h3><?php echo $this->translate('Request example') // TRANSLATE ?></h3>
		<div class="source-panel highlighted-source-panel"><?php echo highlight_string("<?php\n\$client = new \WebAPI\Http\Client(
	'http://localhost:10081/ZendServer/Api/monitorGetIssueDetails',
	array(
		'issueId' => '12',
		'limit' => '10',
	));

\$response = \$client->send()->getBody();", true) ?></div>
		<h3><?php echo $this->translate('Example response') // TRANSLATE ?></h3>
		<div id="monitor_get_issue_details-output-panel" class="source-panel"><code><?php echo nl2br(str_replace(' ','&nbsp',htmlentities('<zendServerAPIResponse xmlns="http://www.zend.com/server/api/1.7">
  <requestData>
    <apiKeyName>admin</apiKeyName>
    <method>applicationGetStatus</method>
  </requestData>
  <responseData>
    <applicationsList>
      <applicationInfo>
        <id>7</id>
        <baseUrl>http://&lt;default-server&gt;/samples</baseUrl>
        <appName>SamplesWebAPI</appName>
        <userAppName>SamplesWebAPI</userAppName>
        <installedLocation>/usr/local/zend/var/apps/http/__default__/0/samples/1.0.0_20</installedLocation>
        <status>deployed</status>
        <isRollbackable>true</isRollbackable>
        <isRedeployable>true</isRedeployable>
        <servers>
          <applicationServer>
            <id>0</id>
            <deployedVersion>1.0.0</deployedVersion>
            <status>deployed</status>
          </applicationServer>
        </servers>
        <deployedVersion>1.0.0</deployedVersion>
        <applicationRollbackVersion>1.0.0</applicationRollbackVersion>
        <messageList></messageList>
        <creationTime>2013-12-25T14:35:46+02:00</creationTime>
        <creationTimeTimestamp>1387974946</creationTimeTimestamp>
        <lastUsed>2013-12-25T14:35:46+02:00</lastUsed>
        <lastUsedTimestamp>1387974946</lastUsedTimestamp>
        <isDefinedApplication>false</isDefinedApplication>
        <vhostId>false</vhostId>
      </applicationInfo>
      <applicationInfo>
        <id>9</id>
        <baseUrl>http://&lt;default-server&gt;:80/webapi-tests</baseUrl>
        <appName>ZendServer-WebapiTests</appName>
        <userAppName>ZendServer-WebapiTests</userAppName>
        <installedLocation>/usr/local/zend/var/apps/http/__default__/0/webapi-tests/1.0.0_12</installedLocation>
        <status>deployed</status>
        <isRollbackable>true</isRollbackable>
        <isRedeployable>true</isRedeployable>
        <servers>
          <applicationServer>
            <id>0</id>
            <deployedVersion>1.0.0</deployedVersion>
            <status>deployed</status>
          </applicationServer>
        </servers>
        <deployedVersion>1.0.0</deployedVersion>
        <applicationRollbackVersion>1.0.0</applicationRollbackVersion>
        <messageList></messageList>
        <creationTime>2013-12-24T10:30:15+02:00</creationTime>
        <creationTimeTimestamp>1387873815</creationTimeTimestamp>
        <lastUsed>2013-12-24T10:30:15+02:00</lastUsed>
        <lastUsedTimestamp>1387873815</lastUsedTimestamp>
        <isDefinedApplication>false</isDefinedApplication>
        <vhostId>false</vhostId>
      </applicationInfo>
    </applicationsList>
  </responseData>
</zendServerAPIResponse>'))) ?>
		</code></div>
	</div></div>
</div>