<div class="samples-panel-group panel-group">
	<div class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('List Deployed Applications') // TRANSLATE ?></h2>
		<p><?php echo sprintf($this->translate('One of the key features of Zend Server, within the scope of %sContinuous Delivery%s, is the ability to deploy application packages on a server or cluster. These applications can then be specifically targetted for monitoring, caching, statistics gathering and many other capabilities that Zend Server provides.'), '<a href="http://www.zend.com/en/solutions/continuous-delivery/" target="_blank">', '</a>') // TRANSLATE ?></p>
		<p><?php echo $this->translate('The most basic activity for working with deployed applications is the ability to query Zend Server about its deployed applications.') // TRANSLATE ?></p>
	
		<h3><?php echo $this->translate('applicationGetStatus: Input Parameters') // TRANSLATE ?></h3>
		<p><?php echo $this->translate('The Web API action applicationGetStatus returns a list of applications according to a set of application IDs. This action can be used to retrieve a full list of applications or just information about a few specific applications.') // TRANSLATE ?></p>
		<h3><?php echo $this->translate('applicationGetStatus: Output Structure') // TRANSLATE ?></h3>
		<p><?php echo $this->translate('The expected output is made out of a list of elements of the type applicationInfo. This element is composed of a few element groups:') // TRANSLATE ?></p>
		<ul>
			<li><?php echo $this->translate('various properties such as &lt;userApplicationName&gt;, &lt;baseUrl&gt;, &lt;installedLocation&gt; and &lt;status&gt;') // TRANSLATE ?></li>
			<li><?php echo $this->translate('&lt;servers&gt; element is a list of servers, in a cluster and the state of their deployed copy of the application. This includes the application version and its status.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('&lt;deployedVersions&gt; element will contain at most two versions of the deployed application.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('&lt;messageList&gt; element will contain messages of varying severity that can give you details about critical and non-critical issues in your application\'s deployment') // TRANSLATE ?></li>
		</ul>
		<h3><?php echo $this->translate('applicationGetStatus Common uses') // TRANSLATE ?></h3>
		<ul>
			<li><?php echo $this->translate('The &lt;status&gt; property is a good way to monitor the general state of the application. Should an application instance fail, anywhere, this error will propagate to the aggregated status element. The messagesList will usually have more details about the exact nature of the problem.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('Using the &lt;servers&gt; list you can monitor each application\'s instance state for every individual server.') // TRANSLATE ?></li>
			<li><?php echo $this->translate('The &lt;deployedVersions&gt; element will indicate which is the current version and which is available for rollback. Using this list you can determine if you can rollback an application and to which version it will end up with.') // TRANSLATE ?></li>
		</ul>
	</div></div>
	<div class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('Web API request example') // TRANSLATE ?></h2>
		<h3><?php echo $this->translate('Request example') // TRANSLATE ?></h3>
		<div class="source-panel highlighted-source-panel"><?php echo highlight_string("<?php\n\$client = new \WebAPI\Http\Client(
	'http://localhost:10081/ZendServer/Api/applicationGetStatus',
	array(
		'key' => '...',
		'keyName' => 'key-name',
	));

\$response = \$client->send()->getBody();", true) ?></div>
		<h3><?php echo $this->translate('Example response') // TRANSLATE ?></h3>
		<div id="application_get_status-output-panel" class="source-panel"><code><?php echo nl2br(str_replace(' ','&nbsp',htmlentities('<zendServerAPIResponse xmlns="http://www.zend.com/server/api/1.7">
  <requestData>
    <apiKeyName>admin</apiKeyName>
    <method>applicationGetStatus</method>
  </requestData>
  <responseData>
    <applicationsList>
      <applicationInfo>
        <id>7</id>
        <baseUrl>http://&lt;default-server&gt;/samples</baseUrl>
        <appName>WebAPI Samples</appName>
        <userAppName>WebAPI Samples</userAppName>
        <installedLocation>/usr/local/zend/var/apps/http/__default__/0/samples/1.0.0_20</installedLocation>
        <status>deployed</status>
        <isRollbackable>true</isRollbackable>
        <isRedeployable>true</isRedeployable>
        <servers>
          <applicationServer>
            <id>0</id>
            <deployedVersion>1.0.0</deployedVersion>
            <status>deployed</status>
          </applicationServer>
        </servers>
        <deployedVersion>1.0.0</deployedVersion>
        <applicationRollbackVersion>1.0.0</applicationRollbackVersion>
        <messageList></messageList>
        <creationTime>2013-12-25T14:35:46+02:00</creationTime>
        <creationTimeTimestamp>1387974946</creationTimeTimestamp>
        <lastUsed>2013-12-25T14:35:46+02:00</lastUsed>
        <lastUsedTimestamp>1387974946</lastUsedTimestamp>
        <isDefinedApplication>false</isDefinedApplication>
        <vhostId>false</vhostId>
      </applicationInfo>
      <applicationInfo>
        <id>9</id>
        <baseUrl>http://&lt;default-server&gt;:80/webapi-tests</baseUrl>
        <appName>ZendServer-WebapiTests</appName>
        <userAppName>ZendServer-WebapiTests</userAppName>
        <installedLocation>/usr/local/zend/var/apps/http/__default__/0/webapi-tests/1.0.0_12</installedLocation>
        <status>deployed</status>
        <isRollbackable>true</isRollbackable>
        <isRedeployable>true</isRedeployable>
        <servers>
          <applicationServer>
            <id>0</id>
            <deployedVersion>1.0.0</deployedVersion>
            <status>deployed</status>
          </applicationServer>
        </servers>
        <deployedVersion>1.0.0</deployedVersion>
        <applicationRollbackVersion>1.0.0</applicationRollbackVersion>
        <messageList></messageList>
        <creationTime>2013-12-24T10:30:15+02:00</creationTime>
        <creationTimeTimestamp>1387873815</creationTimeTimestamp>
        <lastUsed>2013-12-24T10:30:15+02:00</lastUsed>
        <lastUsedTimestamp>1387873815</lastUsedTimestamp>
        <isDefinedApplication>false</isDefinedApplication>
        <vhostId>false</vhostId>
      </applicationInfo>
    </applicationsList>
  </responseData>
</zendServerAPIResponse>'))) ?>
		</code></div>
	</div></div>
</div>