<div class="samples-panel-group panel-group">
	<div class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('Deploying an application zpk') // TRANSLATE ?></h2>
		<p><?php echo sprintf($this->translate('Zend Server\'s UI allows the user to easily deploy an application %szpk package%s using a wizard. The UI wizard does not lend itself to easily integrate with external services, which is why the same functionality is available as a Web API action.'), '<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#application_package.htm">','</a>') // TRANSLATE ?></p>
		<p><?php echo $this->translate('The Web API action allows you to upload the application package, pass its relevant meta information and add any user params needed.') // TRANSLATE ?></p>
		<p><?php echo $this->translate('When the response is returned the application has begun its deployment process.') // TRANSLATE ?></p>
	
		<h3><?php echo $this->translate('applicationDeploy: Input Parameters') // TRANSLATE ?></h3>
		<p><?php echo sprintf($this->translate('applicationDeploy has two mandatory parameters that must be passed for this action to work. This request must also be sent with the "multipart/form-data" content type header.')) // TRANSLATE ?></p>
		<ul>
			<li><?php echo $this->translate('The request has to carry an attached zpk file. This is the package to be deployed and should have the form element name "appPackage".') // TRANSLATE ?></li>
			<li><?php echo $this->translate('The parameter "baseUrl" is needed by Zend Server to assign an access interface, port or vhost for the application.') // TRANSLATE ?></li>
		</ul>
		<p><?php echo sprintf($this->translate('Other parameters are optional but have important effects on your deployment request:')) // TRANSLATE ?></p>
		<ul>
			<li><?php echo $this->translate('If "defaultServer" is set to TRUE the host passed in the baseUrl parameter will be overridden and the default-server value used instead. This means your application will be available from every interface on the webserver. This parameter does not affect port - whatever was specified in the baseUrl will still be used.') // TRANSLATE ?></li>
			<li><?php echo sprintf($this->translate('"userParams" is an array parameter that allows the client to submit an associative array of user parameters. These parameters are specified by the package itself and the values are then made available in its %sinternal hook scripts%s. Should a required user parameter not be provided, an error will be returned and the deployment request aborted.'), '<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#understanding_the_package_structure.htm">','</a>') // TRANSLATE ?></li>
		</ul>
		<h3><?php echo $this->translate('applicationDeploy: Output Structure') // TRANSLATE ?></h3>
		<p><?php echo sprintf($this->translate('The action returns an %sapplicationInfo element%s which contains all information available about the new application.'), '<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#applicationinfo.htm">','</a>') // TRANSLATE ?></p>
		<h3><?php echo $this->translate('applicationDeploy Practices') // TRANSLATE ?></h3>
		<p><?php echo $this->translate('Application deployment automation is usually involved in the organization\'s software life cycle or continuous delivery system. The deployment step could be the final release to production or part of the creation of a standard developer environment.') // TRANSLATE ?></p>
		<p><?php echo $this->translate('Once the applicationDeploy command has been issued, it will take Zend Server some time to complete this operation. Note the status "staging" in our example to the right. The amount of time depends on hook scripts\' execution, the size of the package and the platform running Zend Server.') // TRANSLATE ?></p>
		<p><?php echo $this->translate('Note that baseUrl values are unique - you cannot have two different applications on the same baseUrl.') // TRANSLATE ?></p>
		<p><?php echo $this->translate('Also note that the deployment operation and its outcome will be registered in the Audit Trail, allowing you to revisit the deployment later. Should a deployment fail, the UI will issue a "Deployment Failed" notification.') // TRANSLATE ?></p>
	</div></div>
	<div class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('Web API request example') // TRANSLATE ?></h2>
		<h3><?php echo $this->translate('Important notice!') // TRANSLATE ?></h3>
		<p><?php echo $this->translate('The applicationDeploy Web API action restarts your webserver as part of the deployment process. If you implement polling, bear in mind it will have to be implemented out of the webserver\'s bounds so that it survives and continues past the webserver\'s restart.') // TRANSLATE ?></p>
		<h3><?php echo $this->translate('Request example') // TRANSLATE ?></h3>
		<div class="source-panel highlighted-source-panel"><?php echo highlight_string("<?php\n\$client = new \WebAPI\Http\Client(
	'http://localhost:10081/ZendServer/Api/applicationDeploy',
	array('baseUrl' => 'http://<default-server>/test', 'defaultServer' => 'TRUE'));
\$client->setFileUpload('some-application.zpk', 'appPackage');
\$client->setMethod('POST');
\$response = \$client->send()->getBody();", true) ?></div>
		<h3><?php echo $this->translate('Example response') // TRANSLATE ?></h3>
		<div id="application_deploy-output-panel" class="source-panel"><code><?php echo nl2br(str_replace(' ','&nbsp',htmlentities(
<<<DEPLOYAPP
<?xml version="1.0" encoding="UTF-8"?>
<zendServerAPIResponse xmlns="http://www.zend.com/server/api/1.2"> 
 <requestData> 
  <apiKeyName><![CDATA[admin]]></apiKeyName> 
  <method>applicationDeploy</method> 
 </requestData> 
 <responseData> 
  <applicationInfo> 
   <id>18</id> 
   <baseUrl><![CDATA[http://<default-server>:80/asdfasdf1]]></baseUrl> 
   <appName><![CDATA[sanity]]></appName> 
   <userAppName><![CDATA[asdfasd12346asd]]></userAppName> 
   <installedLocation><![CDATA[]]></installedLocation> 
   <status>staging</status> 
   <isRollbackable>false</isRollbackable> 
   <isRedeployable>false</isRedeployable> 
   <servers>
    <applicationServer> 
     <id>0</id> 
     <deployedVersion>1.0.0</deployedVersion> 
     <status>staging</status> 
    </applicationServer> 
   </servers> 
   <deployedVersion>1.0.0</deployedVersion> 
   <messageList></messageList> 
   <creationTime>2014-01-07T16:56:16+02:00</creationTime> 
   <creationTimeTimestamp>1389106576</creationTimeTimestamp> 
   <lastUsed>2014-01-07T16:56:16+02:00</lastUsed> 
   <lastUsedTimestamp>1389106576</lastUsedTimestamp> 
   <isDefinedApplication>false</isDefinedApplication> 
   <vhostId>false</vhostId> 
  </applicationInfo>
 </responseData>
</zendServerAPIResponse>
DEPLOYAPP
))) ?>
		</code></div>
		<h3><?php echo $this->translate('After deployment...') // TRANSLATE ?></h3>
		<p><?php echo sprintf($this->translate('Track deployment progress by polling Zend Server using the Web API action %sapplicationGetStatus%s. This action allows you to poll a specific application\'s status and wait for it to arrive at some stable state - be it successful completion or an error in deployment.'),'<a href="http://localhost/samples/application/Simple/ListApplications">','</a>') // TRANSLATE ?></p>
	</div></div>
</div>