<div class="samples-panel-group panel-group">
	<div id="siganture-panel" class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('WebAPI error output') // TRANSLATE ?></h2>
		<p><?php echo $this->translate('The WebAPI returns and handles errors in a uniform and standardized way. Whenever an error is detected in execution, be it due to failed input filtering or a concrete logic error in the application, the same error payload is returned. This error display is output-sensitive so that you will get the format you expected when you sent the request.') // TRANSLATE ?></p>
	
		<h3><?php echo $this->translate('Signature hash values') // TRANSLATE ?></h3>
		<h3><?php echo $this->translate('WebAPI Key') // TRANSLATE ?></h3>
		<h3><?php echo $this->translate('Signed Hash') // TRANSLATE ?></h3>
	</div></div>
	<div id="result-panel" class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('WebAPI request signing') // TRANSLATE ?></h2>
		<p><?php echo $this->translate('This example specifically demonstrates the signature creation process and header formatting. In other examples this code is assumed to have been encapsulated elsewhere.') // TRANSLATE ?></p>
		<h3><?php echo $this->translate('Example code') // TRANSLATE ?></h3>
		<div class="source-panel highlighted-source-panel"><?php echo str_replace('&nbsp;&nbsp;', '&nbsp;', highlight_string("<?php\n{$source}", true)) ?></div>
	</div></div>
</div>