<div id="signature-panel-group" class="panel-group">
	<div id="siganture-panel" class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('Signing a WebAPI request') // TRANSLATE ?></h2>
		<p><?php echo $this->translate('Every WebAPI request sent to a launched Zend Server must be accompanied by a signature to authenticate its origin, pass permissions\' check and to verify its contents. The signature is a sha256 hmac keyed by the shared secret WebAPI key. This key is provided by Zend Server after bootstrap or can be created in the UI.') // TRANSLATE ?></p>
	
		<h3><?php echo $this->translate('Signature hash values') // TRANSLATE ?></h3>
			<p><?php echo $this->translate('The WebAPI signature encrypts a hash made out of a few headers and parts of the WebAPI action URL that will be called.') // TRANSLATE ?></p>
			<p><?php echo $this->translate('The Date header must be current - a signature will expire after 5 minutes of its creation and will not be usable.') // TRANSLATE ?></p>
			<p><?php echo $this->translate('The Host header must include the URL port (usually 10081).') // TRANSLATE ?></p>
			<p><?php echo sprintf($this->translate('The WebAPI URL we will request: %shttp://127.0.0.1:10081/ZendServer/Api/getSystemInfo%s'), '<samp>', '</samp>') // TRANSLATE ?></p>
			<ul>
				<li><?php echo $this->translate('Date:') // TRANSLATE ?> <?php echo $date ?> (<code>gmdate('D, d M Y H:i:s') . ' GMT'</code>)<br />
				<em><?php echo $this->translate('Note that the formatted Date value has to be current') // TRANSLATE ?></em></li>
				<li><?php echo $this->translate('User-Agent:') // TRANSLATE ?> <samp><?php echo $useragent ?></samp></li>
				<li><?php echo $this->translate('Host:') // TRANSLATE ?> <samp><?php echo "{$uri->getHost()}:{$uri->getPort()}" ?></samp></li>
				<li><?php echo $this->translate('Path/URI:') // TRANSLATE ?> <samp><?php echo $uri->getPath() ?></samp></li>
			</ul>
		<h3><?php echo $this->translate('WebAPI Key') // TRANSLATE ?></h3>
		<p><?php echo $this->translate('The WebAPI secret key is used to encrypt the signature, we use a key and username that we made up.') // TRANSLATE ?></p>
		<p><?php echo $this->translate('WebAPI key identifier:')?> <samp><?php echo $keyname ?></samp></p>
		<p><?php echo $this->translate('WebAPI secret key:')?> <samp><?php echo $key ?></samp></p>
		<h3><?php echo $this->translate('Signed Hash') // TRANSLATE ?></h3>
		<p><?php echo $this->translate('The signing process creates a hash of all supplied parameters and then encrypts the string into an hmac, using the secret key provided beforehand')?></p>
		<p><?php echo $this->translate('The resulting signature is:')?> <samp><?php echo $finalSignature ?></samp></p>
		<p><?php echo $this->translate('Finally, the X-Zend-Signature header is ready (chopped up for brevity):')?> <code><?php echo $signatureHeaderFormatted ?></code></p>
	</div></div>
	<div id="result-panel" class="panel pull-left"><div class="panel-body">
		<h2><?php echo $this->translate('WebAPI request signing') // TRANSLATE ?></h2>
		<p><?php echo $this->translate('This example specifically demonstrates the signature creation process and header formatting. In other examples this code is assumed to have been encapsulated elsewhere.') // TRANSLATE ?></p>
		<h3><?php echo $this->translate('Example code') // TRANSLATE ?></h3>
		<div class="source-panel highlighted-source-panel"><?php echo str_replace('&nbsp;&nbsp;', '&nbsp;', highlight_string("<?php\n{$source}", true)) ?></div>
	</div></div>
</div>