<?php foreach ($source as $reflected) :?>
<div class="panel">
	<?php if (isset($reflected['uri'])): ?>
	<p><?php echo $this->translate('URI:')?> <a href="<?php echo $this->basepath($reflected['uri']) ?>"><?php echo $this->basepath($reflected['uri']) ?></a></p>
	<?php endif ?>
	<p><?php echo $this->translate('Full filepath:')?> <?php echo $reflected['filepath'] ?></p>
	<div class="source-panel full-size-source"><?php echo highlight_string($reflected['body'], true) ?></div>
</div>
<?php endforeach ?>