<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Zend Server\'s %sWebAPI Samples%s'), '<span class="zf-green">', '</span>') // TRANSLATE ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZend Server WebAPI samples%s application.
    		This application provides you a few examples of what can be done with the WebAPI and how we thought you could use the WebAPI.'), '<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#web_api_reference_guide.htm" target="_blank">', '</a>') // TRANSLATE ?></p>
    <p><a class="btn btn-success btn-lg" href="http://files.zend.com/help/Zend-Server/zend-server.htm#web_api_reference_guide.htm" target="_blank"><?php echo $this->translate('Check our documentation for more information') // TRANSLATE ?> &raquo;</a></p>
</div>

- WebAPI samples by workflow and complexity
  - Basics
    - Signatures
    - Accept header options
    - Error standard output
  - Begginer workflows
    - List applications
    - List events
    - List audit trail
  - Advanced workflows
    - Change directive value, polling
    - Create a vhost, polling
    - Bootstrap a server
- Each sample should expose highlighted code
- Each sample should return a tidied output
- Error handling for samples

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('The Basics') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p class="description"><?php echo sprintf($this->translate('These are code examples and explanations of the basic building blocks of using the WebAPI. These examples do not actually do anything in of themselves, instead they show you the first steps on the road to automation')) // TRANSLATE ?></p>
            	<ul class="list-unstyled list-group">
            		<li class="list-group-item">
            			<a class="" href=""><?php echo $this->translate('Signatures') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#signing_api_requests.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            		<li class="list-group-item">
            			<a href=""><?php echo $this->translate('Accept header & version') // TRANSLATE ?></a>
	            		<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#api_versioning_negotation.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
	            		</div>
            		</li>
            		<li class="list-group-item">
            			<a href=""><?php echo $this->translate('Error standard output') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#response_format.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            	</ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Simple Workflows') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p class="description"><?php echo $this->translate('These code examples show some simple, one step workflows that can be used for retrieving information from Zend Server') // TRANSLATE ?></p>
                <ul class="list-unstyled list-group">
            		<li class="list-group-item">
            			<a class="" href=""><?php echo $this->translate('Signatures') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#signing_api_requests.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            		<li class="list-group-item">
            			<a href=""><?php echo $this->translate('Accept header & version') // TRANSLATE ?></a>
	            		<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#api_versioning_negotation.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
	            		</div>
            		</li>
            		<li class="list-group-item">
            			<a href=""><?php echo $this->translate('Error standard output') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#response_format.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            	</ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Advanced Workflows') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
