<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Zend Server\'s %sWebAPI Samples%s'), '<span class="zf-green">', '</span>') // TRANSLATE ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZend Server WebAPI samples%s application.
    		This application provides you a few examples of what can be done with the WebAPI and how we thought you could use the WebAPI.'), '<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#web_api_reference_guide.htm" target="_blank">', '</a>') // TRANSLATE ?></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('The Basics') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p class="description"><?php echo sprintf($this->translate('These are code examples and explanations of the basic building blocks of using the WebAPI. These examples do not actually do anything in of themselves, instead they show you the first steps on the road to automation')) // TRANSLATE ?></p>
            	<ul class="list-unstyled list-group">
            		<li class="list-group-item">
            			<a href="<?php echo $this->url('application/default', array('controller' => 'Basics', 'action' => 'Signature')) ?>"><?php echo $this->translate('Signatures') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href="<?php echo $this->url('application/source', array('workflow' => 'Basics', 'topic' => 'Signature')) ?>"><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#signing_api_requests.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            		<li class="list-group-item">
            			<a href="<?php echo $this->url('application/default', array('controller' => 'Basics', 'action' => 'VersionNegotiation')) ?>"><?php echo $this->translate('Accept header & version') // TRANSLATE ?></a>
	            		<div class="pull-right">
	            			<a href="<?php echo $this->url('application/source', array('workflow' => 'Basics', 'topic' => 'VersionNegotiation')) ?>"><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#api_versioning_negotation.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
	            		</div>
            		</li>
            		<li class="list-group-item">
            			<a href="<?php echo $this->url('application/default', array('controller' => 'Basics', 'action' => 'ErrorOutput')) ?>"><?php echo $this->translate('Error standard output') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#response_format.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            	</ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Simple Workflows') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p class="description"><?php echo $this->translate('Simple code examples that show some one step workflows that can be used for retrieving information from Zend Server. These actions only require parsing of the response and usually do not require any other activity') // TRANSLATE ?></p>
                <ul class="list-unstyled list-group">
            		<li class="list-group-item">
            			<a href="<?php echo $this->url('application/default', array('controller' => 'Simple', 'action' => 'ListApplications')) ?>"><?php echo $this->translate('List applications') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href="<?php echo $this->url('application/source', array('workflow' => 'Simple', 'topic' => 'ListApplications')) ?>"><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#the_applicationgetstatus_method.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            		<li class="list-group-item">
            			<a href="<?php echo $this->url('application/default', array('controller' => 'Simple', 'action' => 'EventInfo')) ?>"><?php echo $this->translate('Event Information') // TRANSLATE ?></a>
	            		<div class="pull-right">
	            			<a href="<?php echo $this->url('application/source', array('workflow' => 'Simple', 'topic' => 'EventInfo')) ?>"><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#monitorgetissueslistbypredefinedfilter.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
	            		</div>
            		</li>
            		<li class="list-group-item">
            			<a href=""><?php echo $this->translate('List audit trail') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#the_auditgetlist_method.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            	</ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Advanced Workflows') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p class="description"><?php echo $this->translate('Advanced code examples show workflows that are used in the real world to implement automation in various environments. These workflows require more than one step and may become complicated.') // TRANSLATE ?></p>
                <ul class="list-unstyled list-group">
            		<li class="list-group-item">
            			<a href=""><?php echo $this->translate('Polling for completion') // TRANSLATE ?></a>
	            		<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#the_configurationstoredirectives_method.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
	            		</div>
            		</li>
            		<li class="list-group-item">
            			<a href=""><?php echo $this->translate('Deploy an Application') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#the_vhostadd_method.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            		<li class="list-group-item">
            			<a class="" href=""><?php echo $this->translate('Bootstrap Zend Server') // TRANSLATE ?></a>
            			<div class="pull-right">
	            			<a href=""><?php echo $this->translate('Source Code') // TRANSLATE ?></a>
	            			<a href="http://files.zend.com/help/Zend-Server/zend-server.htm#the_bootstrapsingleserver_method.htm" target="_blank"><?php echo $this->translate('doc') // TRANSLATE ?></a>
            			</div>
            		</li>
            	</ul>
            </div>
        </div>
    </div>
</div>
