<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Integrate Web API for ZF2 %sEasily!%s'), '<span class="zf-green">', '</span>') // TRANSLATE ?></h1>
    <p><?php echo sprintf($this->translate('Using the %sZend Server Web API Connector%s ZF2 module you can integrate advanced Web API functionality directly into your application without having to worry about every last detail.'), '<a href="https://github.com/zend-patterns/ZendServerWebApiModule/" target="_blank">', '</a>') // TRANSLATE ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zend-patterns/ZendServerWebApiModule/archive/master.zip" target="_blank"><?php echo $this->translate('Give me some integration goodness!') ?> &raquo;</a></p>
</div>

<div class="row sdk-descriptions">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Start Right Now') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p class=""><?php echo sprintf($this->translate('Zend Framework 2\'s Module Manager allows the Web API Connector to just be dropped into your application and you are good to go.')) // TRANSLATE ?></p>
                <p class=""><?php echo sprintf($this->translate('The Connector is provided as-is from github.com or as a library deployment zpk file, ready to be deployed on your cluster.')) // TRANSLATE ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Simple to Use') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Web API Connector is simple to use, relies on tried-and-tested ZF2 classes and provides you easy access to Zend Server\'s functionality and responses.') // TRANSLATE ?></p>
                <p><?php echo $this->translate('Included in the module is a simple Client class that handles communications and provides uniform responses for easy integration.') // TRANSLATE ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Keep It Rolling') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Zend Server Web API opens the door, Web API Connector kicks it open all the way! Stay up to date with the Web API Connector library and stay abreast with Zend Server\'s advancing Web API versions.') // TRANSLATE ?></p>
                <p><?php echo $this->translate('Every version of Web API introduces something new, keep up with us!') // TRANSLATE ?></p>
            </div>
        </div>
    </div>
</div>