<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('WebAPI Integration for ZF2 is %sEasy!%s'), '<span class="zf-green">', '</span>') // TRANSLATE ?></h1>
    <p><?php echo sprintf($this->translate('Using the %sZend Server WebAPI SDK%s ZF2 module you can integrate advanced WebAPI functionality directly into your application without having to worry about every last detail.'), '<a href="https://github.com/zend-patterns/ZendServerSDK" target="_blank">', '</a>') // TRANSLATE ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zend-patterns/ZendServerSDK/archive/master.zip" target="_blank"><?php echo $this->translate('Give me some integration goodness!') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Start Right Now') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p class="description"><?php echo sprintf($this->translate('Zend Framework 2\'s Module Manager allows the WebAPI SDK to just be dropped into your application and you are good to go.')) // TRANSLATE ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Simple to Use') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('WebAPI SDK is simple to use, relies on tried-and-tested ZF2 classes and provides you easy access to Zend Server\'s functionality and responses. The responses are uniform in structure and content, error handling is standardized.') // TRANSLATE ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Keep It Rolling') // TRANSLATE ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Zend Server WebAPI opens the door, WebAPI SDK kicks it open all the way! Stay up to date with the WebAPI SDK library and stay abreast with Zend Server\'s advancing WebAPI versions.') // TRANSLATE ?></p>
                <p><?php echo $this->translate('Every version of WebAPI introduces something new, keep up with us!') // TRANSLATE ?></p>
            </div>
        </div>
    </div>
</div>